// Command gendocs regenerates the Markdown command reference under docs/ from the
// Cobra command tree, so the reference always matches `wtm <cmd> --help`.
//
// Run it with `make docs` (or `go run ./tools/gendocs`). The generated files are
// checked in; regenerate on any command-surface change.
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/LucasPcq/wtm/cmd"
	"github.com/LucasPcq/wtm/internal/domain"
)

const outputDir = "docs"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(domain.ExitCodeError)
	}
}

func run() error {
	root := cmd.Root()
	disableAutoGenTag(root)

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}

	if err := doc.GenMarkdownTree(root, outputDir); err != nil {
		return err
	}
	return writeIndex(root)
}

// disableAutoGenTag strips the timestamped "Auto generated by spf13/cobra"
// footer from every command so regenerating the docs produces no date churn.
func disableAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true
	for _, child := range c.Commands() {
		disableAutoGenTag(child)
	}
}
